name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2.3.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Prettier
        uses: MansaGroup/nrwl-nx-action@v1.0.1
        with:
          targets: format:check
          all: 'true'
          parallel: 'true'
      - name: Lint
        uses: MansaGroup/nrwl-nx-action@v1.0.1
        with:
          targets: lint
          all: 'true'
          parallel: 'true'
      - name: Test
        uses: MansaGroup/nrwl-nx-action@v1.0.1
        with:
          targets: test
          all: 'true'
          parallel: 'true'
      - name: Build
        uses: MansaGroup/nrwl-nx-action@v1.0.1
        with:
          targets: build
          all: 'true'
          parallel: 'true'
          args: '--prod=true --base-href=/pokedex-ng/'
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/pokedex-ng
