name: Deploy

on:
  push:
    branches:
      - master

jobs:
  verify:
    uses: fsancheztemprano/pokedex-ng/.github/workflows/Verify.yml@master

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Use Node 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14'

      - name: Cache Node modules
        uses: fsancheztemprano/always-cache@main
        env:
          cache-key: ${{ runner.os }}-yarn-v2
        with:
          path: |
            ~/.npm
            ./node_modules
            ./node
          key: ${{ env.cache-key }}-${{ steps.branch-name.outputs.current_branch }}-${{ hashFiles('**/yarn.lock') }}-${{ github.run_id }}
          restore-keys: |
            ${{ env.cache-key }}-${{ steps.branch-name.outputs.current_branch }}-${{ hashFiles('**/yarn.lock') }}-
            ${{ env.cache-key }}-${{ steps.branch-name.outputs.current_branch }}-
            ${{ env.cache-key }}-
          save-on-hit: true

      - name: Yarn Install
        run: yarn install

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ng -- deploy --base-href=/pokedex-ng/ --no-silent
