name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Yarn Install
        run: yarn install

      - name: Prettier
        uses: MansaGroup/nrwl-nx-action@v1.0.1
        with:
          targets: format:check
          all: 'true'
          parallel: 'true'
          affected: 'false'

      - name: Lint
        uses: MansaGroup/nrwl-nx-action@v1.0.1
        with:
          targets: lint
          all: 'true'
          parallel: 'true'
          affected: 'false'

      - name: Test
        uses: MansaGroup/nrwl-nx-action@v1.0.1
        with:
          targets: test
          all: 'true'
          parallel: 'true'
          affected: 'false'

      - name: Build
        run: yarn run build:prod

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/apps/pokedex-ng
