name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Use Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn Install
        run: yarn install
      - name: Prettier
        uses: MansaGroup/nrwl-nx-action@v2.0.3
        with:
          targets: format:check
          all: 'true'
          parallel: 'true'
          affected: 'false'
      - name: Lint
        uses: MansaGroup/nrwl-nx-action@v2.0.3
        with:
          targets: lint
          all: 'true'
          parallel: 'true'
          affected: 'false'
      - name: Test
        uses: MansaGroup/nrwl-nx-action@v2.0.3
        with:
          targets: test
          all: 'true'
          parallel: 'true'
          affected: 'false'
      - name: Build
        uses: MansaGroup/nrwl-nx-action@v1.0.1
        with:
          targets: build
          all: 'true'
          parallel: 'true'
          affected: 'false'
          args: '--prod=true --base-href=/pokedex-ng/'
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run ng -- deploy --base-href=/pokedex-ng/ --no-silent
