name: Deploy

on:
  workflow_run:
    workflows: ["Verify"]
    branches: [master]    
    types: 
      - completed
      - requested

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.x
      - run: npm install
      - run: npm run deploy
